/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallRouteImport } from './routes/install'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as SubsRouteImport } from './routes/subs'
import { Route as YouRouteImport } from './routes/you'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const SubsRoute = SubsRouteImport.update({
  id: '/subs',
  path: '/subs',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/shorts': typeof ShortsRoute
  '/subs': typeof SubsRoute
  '/you': typeof YouRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/shorts': typeof ShortsRoute
  '/subs': typeof SubsRoute
  '/you': typeof YouRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/shorts': typeof ShortsRoute
  '/subs': typeof SubsRoute
  '/you': typeof YouRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/install' | '/shorts' | '/subs' | '/you' | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/install' | '/shorts' | '/subs' | '/you' | '/watch/$id'
  id:
    '__root__' | '/' | '/install' | '/shorts' | '/subs' | '/you' | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRoute: typeof InstallRoute
  ShortsRoute: typeof ShortsRoute
  SubsRoute: typeof SubsRoute
  YouRoute: typeof YouRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subs': {
      id: '/subs'
      path: '/subs'
      fullPath: '/subs'
      preLoaderRoute: typeof SubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRoute: InstallRoute,
  ShortsRoute: ShortsRoute,
  SubsRoute: SubsRoute,
  YouRoute: YouRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
